[tool.poetry]
name = "dracor-metrics"
version = "1.3.2"
description = "Microservice calculating network metrics for dracor.org."
authors = ["Carsten Milling <cmil@hashtable.de>"]
license = "MIT"
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "~3.11"
hug = "^2.6.1"
networkx = "^3.2.1"
waitress = "^2.1.2"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
